substitutions:
  name: bluetooth-proxy-lr
  friendly_name: bluetooth-proxy-living-room

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.2.1
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    # https://github.com/esphome/bluetooth-proxies/releases
    version: "25.3.1"  

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# Enable logging
logger:
improv_serial:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bluetooth_proxy_lr_esp_api_encryption_key

ota:
  - platform: esphome
    password: !secret bluetooth_proxy_lr_esp_ota_password
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret bluetooth_proxy_lr_wifi_manual_ip_static_ip
    gateway: !secret wifi_manual_ip_gateway
    subnet: !secret wifi_manual_ip_subnet
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret bluetooth_proxy_lr_wifi_ap_ssid
    password: !secret bluetooth_proxy_lr_wifi_ap_password

captive_portal:
  
update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/bluetooth-proxy/m5stack-atom-lite/manifest.json

http_request:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-lite.yaml@main

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
