---
substitutions:
  device_static_ip: !secret soil_sensor_tuyas_wifi_manual_ip_static_ip
  device_ap_ssid: !secret soil_sensor_tuyas_wifi_ap_ssid
  device_ap_password: !secret soil_sensor_tuyas_wifi_ap_password
  wifi_ssid: !secret wifi2_ssid
  wifi_password: !secret wifi_password
  wifi_manual_ip_gateway: !secret wifi_manual_ip_gateway
  wifi_manual_ip_subnet: !secret wifi_manual_ip_subnet
  esp_api_encryption_key: !secret soil_sensor_tuyas_esp_api_encryption_key
  esp_ota_password: !secret soil_sensor_tuyas_esp_ota_password

  ota_update_entity_id: input_boolean.soil_sensor_tuyas_ota_updates

  zero_calibration_voltage: "0.84"
  full_calibration_voltage: "1.64"

packages:
  bt_proxy: !include packages/device-configs/soil-sensor-d1-mini.yaml
