substitutions:  
  device_static_ip: !secret soil_sensor_tuyas_wifi_manual_ip_static_ip
  device_ap_ssid: !secret soil_sensor_tuyas_wifi_ap_ssid
  device_ap_password: !secret soil_sensor_tuyas_wifi_ap_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_manual_ip_gateway: !secret wifi_manual_ip_gateway
  wifi_manual_ip_subnet: !secret wifi_manual_ip_subnet


esphome:
  name: soil-sensor-tuyas
  friendly_name: soil-sensor-tuyas

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret soil_sensor_tuyas_esp_api_encryption_key

ota:
  - platform: esphome
    password: !secret soil_sensor_tuyas_esp_ota_password

packages:
  wifi: !include packages/wifi.yaml

captive_portal:
