---
# Example Electric Meter Configuration
# This demonstrates how to use the electric-meter package with different settings

substitutions:
  name: my-electric-meter
  friendly_name: My Electric Meter
  device_static_ip: 192.168.1.100
  device_ap_ssid: "MyMeter-AP"
  device_ap_password: "mypassword123"
  wifi_ssid: "MyWiFiNetwork"
  wifi_password: "mywifipass"
  wifi_manual_ip_gateway: 192.168.1.1
  wifi_manual_ip_subnet: 255.255.255.0
  
  # MQTT Configuration
  mqtt_broker: "192.168.1.50"        # Your MQTT broker IP/hostname
  mqtt_username: "esphome"           # Your MQTT username
  mqtt_password: "your_mqtt_password" # Your MQTT password
  mqtt_topic_prefix: "esphome/my-electric-meter" # MQTT topic prefix for this device

  # UART Configuration - adjust these for your meter
  uart_rx_pin: "D5"           # Change to your RX pin
  uart_baud_rate: "2400"      # Common alternatives: 1200, 2400, 4800, 9600
  uart_parity: "NONE"         # Common alternatives: EVEN, ODD, NONE
  uart_data_bits: "8"         # Common alternatives: 7, 8
  uart_stop_bits: "1"         # Usually 1
  uart_rx_buffer_size: "512"  # Adjust if needed

  # Sensor Group Control (set to "true" to disable processing and hide by default)
  # Enable/disable entire sensor groups to optimize performance and reduce clutter
  disabled_core_sensors: "false"                      # Total consumption, current power (keep enabled for basic functionality)
  disabled_feed_in_sensors: "false"                   # Total feed-in (set to "true" if no solar installation)
  disabled_voltage_sensors: "false"                   # L1, L2, L3 voltage sensors
  disabled_current_sensors: "false"                   # L1, L2, L3 current sensors
  disabled_frequency_sensors: "false"                 # Grid frequency sensor
  disabled_phase_angle_sensors: "true"                # Phase angle sensors (advanced use only)
  disabled_tariff_sensors: "false"                    # T1, T2 tariff consumption sensors
  disabled_consumption_since_reset_sensors: "true"    # Consumption since reset sensor
  disabled_rolling_window_sensors: "false"            # 1d, 7d, 30d, 365d consumption sensors
  disabled_diagnostic_sensors: "false"                # Serial number, firmware version, etc.
  disabled_quality_sensors: "false"                   # Communication quality monitoring

  # OBIS codes - these are specific to your meter model
  # Check your meter's documentation for the correct codes
  obis_total_consumption: "1-0:1.8.0*255"
  obis_total_feed_in: "1-0:2.8.0*255"          # For solar installations (total feed-in)
  obis_consumption_1d: "1-0:1.8.0*96"
  obis_consumption_7d: "1-0:1.8.0*97"
  obis_consumption_30d: "1-0:1.8.0*98"
  obis_consumption_365d: "1-0:1.8.0*99"
  obis_current_power: "1-0:16.7.0*255"
  obis_consumption_t1: "1-0:1.8.1*255"
  obis_consumption_t2: "1-0:1.8.2*255"
  obis_voltage_l1: "1-0:32.7.0*255"
  obis_voltage_l2: "1-0:52.7.0*255"
  obis_voltage_l3: "1-0:72.7.0*255"
  obis_current_l1: "1-0:31.7.0*255"
  obis_current_l2: "1-0:51.7.0*255"
  obis_current_l3: "1-0:71.7.0*255"
  obis_frequency: "1-0:14.7.0*255"
  obis_phase_angle_ul2_ul1: "1-0:81.7.1*255"
  obis_phase_angle_ul3_ul1: "1-0:81.7.2*255"
  obis_phase_angle_il1_ul1: "1-0:81.7.4*255"
  obis_phase_angle_il2_ul2: "1-0:81.7.15*255"
  obis_phase_angle_il3_ul3: "1-0:81.7.26*255"
  obis_serial_number: "1-0:96.1.0*255"
  obis_firmware_version: "1-0:0.2.0*255"
  obis_parameter_crc: "1-0:96.90.2*255"
  obis_status_register: "1-0:97.97.0*255"
  obis_consumption_since_reset: "1-0:1.8.0*100"

  # Validation constants - adjust for your installation
  max_power_change: "5000.0"           # 5kW max power change per reading
  max_current_change: "20.0"           # 20A max current change per reading
  max_energy_change: "2.0"             # 2 kWh max energy change per reading
  max_rolling_energy_change: "2.0"     # 2 kWh max change for rolling window sensors
  max_energy_total: "200000.0"         # 200,000 kWh lifetime maximum
  max_absolute_power: "50000.0"        # 50kW absolute maximum
  min_energy_value: "0.0"
  min_power_value: "0.0"
  max_voltage: "280.0"                 # 280V max voltage
  min_voltage: "180.0"                 # 180V min voltage (adjust for your grid)
  max_current: "40.0"                  # 40A max current
  min_current: "0.0"
  max_frequency: "55.0"                # 55Hz max frequency
  min_frequency: "45.0"                # 45Hz min frequency
  max_phase_angle: "360.0"
  min_phase_angle: "-360.0"

  # Rolling Window Maximum Values (adjust based on your household consumption)
  max_consumption_1d: "30.0"          # 30 kWh max daily consumption
  max_consumption_7d: "210.0"         # 210 kWh max weekly consumption
  max_consumption_30d: "800.0"        # 800 kWh max monthly consumption
  max_consumption_365d: "10000.0"     # 10,000 kWh max yearly consumption

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0

# Required for uart_line_reader and deduplicate_text components used by electricity-meter package
# Uncomment if you have the custom components directory:
# external_components:
#   - source:
#       type: local
#       path: components

esp8266:
  board: nodemcu  # or d1_mini, wemos_d1_mini32, etc.

# Enable logging
logger:
  level: INFO  # Change to DEBUG for more verbose logging

# Enable Home Assistant API
api:
  password: "your_api_password"

# Enable OTA updates
ota:
  - platform: esphome
    password: "your_ota_password"

# WiFi configuration
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  manual_ip:
    static_ip: ${device_static_ip}
    gateway: ${wifi_manual_ip_gateway}
    subnet: ${wifi_manual_ip_subnet}
  ap:
    ssid: ${device_ap_ssid}
    password: ${device_ap_password}

# Import packages
packages:
  # WiFi configuration (you'll need to create this or use existing)
  # wifi: !include ../../wifi.yaml
  # wifi-signal-sensors: !include ../../wifi-signal-sensors.yaml
  
  # MQTT configuration
  mqtt: !include ../../mqtt.yaml
  mqtt-diagnostic-sensors: !include ../../mqtt-diagnostic-sensors.yaml
  
  # Electricity meter package
  electricity-meter: !include ../electricity-meter.yaml

# Optional: Add a status LED
status_led:
  pin:
    number: D4
    inverted: true

# Example sensor group configurations:
# 
# For a basic installation (only essential sensors):
# disabled_core_sensors: "false"
# disabled_feed_in_sensors: "true"
# disabled_voltage_sensors: "true"
# disabled_current_sensors: "true"
# disabled_frequency_sensors: "true"
# disabled_phase_angle_sensors: "true"
# disabled_tariff_sensors: "true"
# disabled_consumption_since_reset_sensors: "true"
# disabled_rolling_window_sensors: "true"
# disabled_diagnostic_sensors: "true"
# disabled_quality_sensors: "true"
#
# For a solar installation:
# disabled_core_sensors: "false"
# disabled_feed_in_sensors: "false"  # Enable to track solar feed-in
# disabled_voltage_sensors: "false"
# disabled_current_sensors: "false"
# disabled_frequency_sensors: "false"
# disabled_phase_angle_sensors: "true"
# disabled_tariff_sensors: "false"
# disabled_consumption_since_reset_sensors: "true"
# disabled_rolling_window_sensors: "false"
# disabled_diagnostic_sensors: "false"
# disabled_quality_sensors: "false"
#
# For advanced monitoring (all sensors):
# disabled_core_sensors: "false"
# disabled_feed_in_sensors: "false"
# disabled_voltage_sensors: "false"
# disabled_current_sensors: "false"
# disabled_frequency_sensors: "false"
# disabled_phase_angle_sensors: "false"
# disabled_tariff_sensors: "false"
# disabled_consumption_since_reset_sensors: "false"
# disabled_rolling_window_sensors: "false"
# disabled_diagnostic_sensors: "false"
# disabled_quality_sensors: "false" 